// Mocks generated by Mockito 5.0.15 from annotations
// in search_in_quran/test/features/ayah_search/usecases/get_ayah_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:search_in_quran/core/error/failure.dart' as _i5;
import 'package:search_in_quran/features/ayah_search/domain/entities/ayah.dart'
    as _i6;
import 'package:search_in_quran/features/ayah_search/domain/entities/ayah_translation.dart'
    as _i7;
import 'package:search_in_quran/features/ayah_search/domain/repository/ayah_search_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [AyahSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAyahSearchRepository extends _i1.Mock
    implements _i3.AyahSearchRepository {
  MockAyahSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Ayah>> getAyah(String? query) =>
      (super.noSuchMethod(Invocation.method(#getAyah, [query]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.Ayah>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Ayah>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Ayah>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.AyahTranslation>> getAyahTranslation(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#getAyahTranslation, [query]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i7.AyahTranslation>>.value(
                      _FakeEither_0<_i5.Failure, _i7.AyahTranslation>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i7.AyahTranslation>>);
  @override
  String toString() => super.toString();
}
